// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/test.proto
// Protobuf Java Version: 4.27.3

package com.goplay.example.dto;

public interface SCTimeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dto.SCTimeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 ServerUtc = 1;</code>
   * @return The serverUtc.
   */
  int getServerUtc();
}
