// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/test.proto
// Protobuf Java Version: 4.27.3

package com.goplay.example.dto;

/**
 * Protobuf type {@code dto.SCTimeInfo}
 */
public final class SCTimeInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:dto.SCTimeInfo)
    SCTimeInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 3,
      /* suffix= */ "",
      SCTimeInfo.class.getName());
  }
  // Use SCTimeInfo.newBuilder() to construct.
  private SCTimeInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SCTimeInfo() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.goplay.example.dto.NetworkDto.internal_static_dto_SCTimeInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.goplay.example.dto.NetworkDto.internal_static_dto_SCTimeInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.goplay.example.dto.SCTimeInfo.class, com.goplay.example.dto.SCTimeInfo.Builder.class);
  }

  public static final int SERVERUTC_FIELD_NUMBER = 1;
  private int serverUtc_ = 0;
  /**
   * <code>int32 ServerUtc = 1;</code>
   * @return The serverUtc.
   */
  @java.lang.Override
  public int getServerUtc() {
    return serverUtc_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (serverUtc_ != 0) {
      output.writeInt32(1, serverUtc_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (serverUtc_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, serverUtc_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.goplay.example.dto.SCTimeInfo)) {
      return super.equals(obj);
    }
    com.goplay.example.dto.SCTimeInfo other = (com.goplay.example.dto.SCTimeInfo) obj;

    if (getServerUtc()
        != other.getServerUtc()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVERUTC_FIELD_NUMBER;
    hash = (53 * hash) + getServerUtc();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.goplay.example.dto.SCTimeInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.goplay.example.dto.SCTimeInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.goplay.example.dto.SCTimeInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.goplay.example.dto.SCTimeInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.goplay.example.dto.SCTimeInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.goplay.example.dto.SCTimeInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.goplay.example.dto.SCTimeInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.goplay.example.dto.SCTimeInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.goplay.example.dto.SCTimeInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.goplay.example.dto.SCTimeInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.goplay.example.dto.SCTimeInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.goplay.example.dto.SCTimeInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.goplay.example.dto.SCTimeInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dto.SCTimeInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dto.SCTimeInfo)
      com.goplay.example.dto.SCTimeInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.goplay.example.dto.NetworkDto.internal_static_dto_SCTimeInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.goplay.example.dto.NetworkDto.internal_static_dto_SCTimeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.goplay.example.dto.SCTimeInfo.class, com.goplay.example.dto.SCTimeInfo.Builder.class);
    }

    // Construct using com.goplay.example.dto.SCTimeInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      serverUtc_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.goplay.example.dto.NetworkDto.internal_static_dto_SCTimeInfo_descriptor;
    }

    @java.lang.Override
    public com.goplay.example.dto.SCTimeInfo getDefaultInstanceForType() {
      return com.goplay.example.dto.SCTimeInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.goplay.example.dto.SCTimeInfo build() {
      com.goplay.example.dto.SCTimeInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.goplay.example.dto.SCTimeInfo buildPartial() {
      com.goplay.example.dto.SCTimeInfo result = new com.goplay.example.dto.SCTimeInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.goplay.example.dto.SCTimeInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.serverUtc_ = serverUtc_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.goplay.example.dto.SCTimeInfo) {
        return mergeFrom((com.goplay.example.dto.SCTimeInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.goplay.example.dto.SCTimeInfo other) {
      if (other == com.goplay.example.dto.SCTimeInfo.getDefaultInstance()) return this;
      if (other.getServerUtc() != 0) {
        setServerUtc(other.getServerUtc());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              serverUtc_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int serverUtc_ ;
    /**
     * <code>int32 ServerUtc = 1;</code>
     * @return The serverUtc.
     */
    @java.lang.Override
    public int getServerUtc() {
      return serverUtc_;
    }
    /**
     * <code>int32 ServerUtc = 1;</code>
     * @param value The serverUtc to set.
     * @return This builder for chaining.
     */
    public Builder setServerUtc(int value) {

      serverUtc_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ServerUtc = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerUtc() {
      bitField0_ = (bitField0_ & ~0x00000001);
      serverUtc_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:dto.SCTimeInfo)
  }

  // @@protoc_insertion_point(class_scope:dto.SCTimeInfo)
  private static final com.goplay.example.dto.SCTimeInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.goplay.example.dto.SCTimeInfo();
  }

  public static com.goplay.example.dto.SCTimeInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SCTimeInfo>
      PARSER = new com.google.protobuf.AbstractParser<SCTimeInfo>() {
    @java.lang.Override
    public SCTimeInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SCTimeInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SCTimeInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.goplay.example.dto.SCTimeInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

